"""Initial Migrations

Revision ID: 19b004f82aa5
Revises: 
Create Date: 2023-06-01 19:52:58.991233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b004f82aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fir',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('PoliceStation', sa.String(length=20), nullable=False),
    sa.Column('place', sa.String(length=20), nullable=False),
    sa.Column('crime', sa.String(length=20), nullable=False),
    sa.Column('DoL', sa.String(length=10), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('police',
    sa.Column('PoliceStation', sa.String(length=20), nullable=False),
    sa.Column('District', sa.String(length=20), nullable=False),
    sa.Column('PhNo', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('PoliceStation'),
    sa.UniqueConstraint('PoliceStation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('police')
    op.drop_table('fir')
    # ### end Alembic commands ###
